version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./logs:/app/logs
      - ./models:/app/models
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=sqlite:///./checks.db
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  streamlit:
    build: 
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - API_URL=http://web:5000
    depends_on:
      - web

volumes:
  redis_data: 